services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secure_password
      MYSQL_DATABASE: data
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"